-- ============================================================
-- MADERA LABRADA — Seed Data
-- Productos, Categorías y Habitaciones
-- ============================================================

-- ── Categorías de producto ──────────────────────────────────
CREATE TABLE IF NOT EXISTS categorias_producto (
  id SERIAL PRIMARY KEY,
  nombre TEXT UNIQUE NOT NULL
);

INSERT INTO categorias_producto (nombre) VALUES
  ('BAR'),('BAZAR'),('BEBIDAS'),('COCINA'),('GOLOSINAS')
ON CONFLICT (nombre) DO NOTHING;

-- ── Tipos de habitación ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS tipos_habitacion (
  id SERIAL PRIMARY KEY,
  nombre TEXT UNIQUE NOT NULL,
  tiene_aire BOOLEAN DEFAULT FALSE
);

INSERT INTO tipos_habitacion (nombre, tiene_aire) VALUES
  ('Simple',          FALSE),
  ('Doble',           FALSE),
  ('Triple',          FALSE),
  ('Cuádruple',       FALSE),
  ('Quíntuple',       FALSE),
  ('Simple C/ Aire',  TRUE),
  ('Doble C/ Aire',   TRUE),
  ('Triple C/ Aire',  TRUE),
  ('Cuádruple C/ Aire', TRUE),
  ('Quíntuple C/ Aire', TRUE)
ON CONFLICT (nombre) DO NOTHING;

-- ── Habitaciones físicas ────────────────────────────────────
CREATE TABLE IF NOT EXISTS habitaciones (
  id SERIAL PRIMARY KEY,
  nombre TEXT UNIQUE NOT NULL,
  tipo TEXT REFERENCES tipos_habitacion(nombre),
  bloque TEXT,
  estado TEXT DEFAULT 'Disponible' CHECK (estado IN ('Disponible','Ocupado','Limpieza','Mantenimiento')),
  activo BOOLEAN DEFAULT TRUE
);

INSERT INTO habitaciones (nombre, tipo, bloque) VALUES
  ('103',      'Simple',           'Bloque 1'),
  ('104',      'Doble',            'Bloque 1'),
  ('105',      'Doble',            'Bloque 1'),
  ('106',      'Doble',            'Bloque 1'),
  ('107',      'Triple',           'Bloque 1'),
  ('201',      'Simple',           'Bloque 2'),
  ('202',      'Doble',            'Bloque 2'),
  ('203',      'Doble',            'Bloque 2'),
  ('PALMITO',  'Triple',           'Bloque 2'),
  ('204',      'Simple',           'Bloque 2'),
  ('205',      'Simple',           'Bloque 2'),
  ('206',      'Simple',           'Bloque 2'),
  ('MIRADOR',  'Cuádruple C/ Aire','Bloque 2'),
  ('ORQUIDEA', 'Triple',           'Bloque 2'),
  ('GIRASOL',  'Cuádruple C/ Aire','Bloque 2'),
  ('FIKUS',    'Doble',            'Bloque 2'),
  ('PALMERAS', 'Triple',           'Bloque 2'),
  ('TULIPAN',  'Doble',            'Bloque 2'),
  ('PIJUAYO',  'Quíntuple',        'Bloque 2'),
  ('BEGONIA',  'Cuádruple C/ Aire','Bloque 2'),
  ('BAMBU',    'Quíntuple C/ Aire','Bloque 2'),
  ('CAOBA',    'Cuádruple C/ Aire','Bloque 2'),
  ('QUINILLA', 'Cuádruple C/ Aire','Bloque 2'),
  ('CEDRO',    'Cuádruple C/ Aire','Bloque 2'),
  ('CROTON',   'Cuádruple C/ Aire','Bloque 2'),
  ('BIJAO',    'Simple',           'Bloque 2'),
  ('HUAYRURO', 'Doble',            'Bloque 2'),
  ('ALMENDRA', 'Simple',           'Bloque 2'),
  ('CACTUS',   'Triple',           'Bloque 2'),
  ('DALIA',    'Quíntuple C/ Aire','Bloque 2')
ON CONFLICT (nombre) DO NOTHING;

-- ── Productos (243) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS productos (
  id SERIAL PRIMARY KEY,
  codigo TEXT UNIQUE NOT NULL,
  nombre TEXT NOT NULL,
  categoria TEXT REFERENCES categorias_producto(nombre),
  precio_compra NUMERIC(10,2) DEFAULT 0,
  precio_venta NUMERIC(10,2) DEFAULT 0,
  proveedor TEXT,
  stock_actual INTEGER DEFAULT 0,
  stock_minimo INTEGER DEFAULT 5,
  activo BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO productos (codigo, nombre, categoria, precio_compra, precio_venta, proveedor) VALUES
  ('PRO-001', 'INKA KOLA PERSONAL', 'BEBIDAS', 0.0, 5.0, 'Mercado'),
  ('PRO-063', 'COCA COLA PERSONAL', 'BEBIDAS', 0.0, 5.0, 'Mercado'),
  ('PRO-064', 'AGUA PERSONAL', 'BEBIDAS', 0.0, 4.0, 'Mercado'),
  ('PRO-065', 'AGUA PERSONAL C/ GAS', 'BEBIDAS', 0.0, 4.0, 'Mercado'),
  ('PRO-066', 'CORONA', 'BEBIDAS', 0.0, 10.0, 'Mercado'),
  ('PRO-067', 'CORONITA', 'BEBIDAS', 0.0, 7.0, 'Mercado'),
  ('PRO-068', 'PILSEN LATA', 'BEBIDAS', 0.0, 7.0, 'Mercado'),
  ('PRO-069', 'SAN JUAN LATA', 'BEBIDAS', 0.0, 7.0, 'Mercado'),
  ('PRO-070', 'CUSQUEÑA TRIGO LATA', 'BEBIDAS', 0.0, 7.0, 'Mercado'),
  ('PRO-071', 'GUARANA', 'BEBIDAS', 0.0, 4.0, 'Mercado'),
  ('PRO-072', 'MALTIN', 'BEBIDAS', 0.0, 2.0, 'Mercado'),
  ('PRO-073', 'PICARAS', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-074', 'SADA V', 'GOLOSINAS', 0.0, 1.0, 'Mercado'),
  ('PRO-075', 'MOROCHAS', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-076', 'CANCUN', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-077', 'CHOCMAN AZUL', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-078', 'CHOCMAN BLANCO', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-079', 'RITZ PEQUEÑO', 'GOLOSINAS', 0.0, 1.5, 'Inmaculada'),
  ('PRO-080', 'RITZ TACO', 'GOLOSINAS', 0.0, 2.5, 'Inmaculada'),
  ('PRO-081', 'SALTICAS', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-082', 'PINGÜINO', 'GOLOSINAS', 0.0, 5.0, 'Mercado'),
  ('PRO-083', 'WAFER GR', 'GOLOSINAS', 0.0, 2.5, 'Inmaculada'),
  ('PRO-084', 'CHIPS AHOY', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-085', 'MARGARITA', 'GOLOSINAS', 0.0, 2.0, 'Inmaculada'),
  ('PRO-086', 'GOLPE', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-087', 'PIQUEO', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-088', 'CHEETOS', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-089', 'PAPAS LAYS', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-090', 'DORITOS', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-091', 'CHEESE TRIS', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-092', 'HALLS', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-093', 'TRIDENT', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-094', 'OLE OLE', 'GOLOSINAS', 0.0, 0.5, 'Mercado'),
  ('PRO-095', 'SUBLIME-STICK', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-096', 'SUBLIME-CLASICO', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-097', 'BLOQUEADOR 90', 'BAZAR', 0.0, 4.5, 'Mercado'),
  ('PRO-099', 'JABON', 'BAZAR', 0.0, 6.0, 'Mercado'),
  ('PRO-0100', 'PEINE', 'BAZAR', 0.0, 3.0, 'Mercado'),
  ('PRO-101', 'CEPILLO', 'BAZAR', 0.0, 5.0, 'Mercado'),
  ('PRO-102', 'COLETTE', 'BAZAR', 0.0, 3.0, 'Mercado'),
  ('PRO-103', 'PASTA DENTAL', 'BAZAR', 0.0, 5.0, 'Mercado'),
  ('PRO-104', 'RASURADOR', 'BAZAR', 0.0, 5.0, 'Mercado'),
  ('PRO-105', 'SHAMPOO', 'BAZAR', 0.0, 3.0, 'Mercado'),
  ('PRO-106', 'DESODORANTE', 'BAZAR', 0.0, 1.5, 'Mercado'),
  ('PRO-107', 'TOALLA H. - NOCHE', 'BAZAR', 0.0, 3.0, 'Mercado'),
  ('PRO-108', 'AGUA 2.5LT', 'BEBIDAS', 0.0, 8.0, 'Mercado'),
  ('PRO-109', 'COCA COLA 1.5LT', 'BEBIDAS', 0.0, 10.0, 'Mercado'),
  ('PRO-110', 'COCA COLA 2.5LT', 'BEBIDAS', 0.0, 15.0, 'Mercado'),
  ('PRO-111', 'INKA KOLA 1.5LT', 'BEBIDAS', 0.0, 10.0, 'Mercado'),
  ('PRO-112', 'INKA KOLA 2.5LT', 'BEBIDAS', 0.0, 15.0, 'Mercado'),
  ('PRO-113', 'Mixto cecina y chorizo', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-114', '2 Cecinas', 'COCINA', 0.0, 32.0, 'Mercado'),
  ('PRO-115', '2 Chorizos', 'COCINA', 0.0, 28.0, 'Mercado'),
  ('PRO-116', 'Chacarero', 'COCINA', 0.0, 60.0, 'Mercado'),
  ('PRO-117', 'Chaufa regional', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-118', 'Salchipapa regional', 'COCINA', 0.0, 28.0, 'Mercado'),
  ('PRO-119', 'Salchipapa simple', 'COCINA', 0.0, 12.0, 'Mercado'),
  ('PRO-120', 'Arroz a la cubana', 'COCINA', 0.0, 12.0, 'Mercado'),
  ('PRO-121', 'Paiche a la Plancha', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-122', 'Paiche al Ajo', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-123', 'Paiche a lo Macho', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-124', 'Ceviche de Paiche', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-125', 'Chicharrón de Paiche', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-126', 'Sudado de Paiche', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-127', 'Tilapia frita', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-128', 'Sudado de Tilapia', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-129', 'Chilcano de Tilapia', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-130', 'Tilapia a lo Macho', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-131', 'Doncella a la Plancha', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-132', 'Chicharrón de Doncella', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-133', 'Sudado de Doncella', 'COCINA', 0.0, 45.0, 'Mercado'),
  ('PRO-134', 'Espagueti al Alfredo', 'COCINA', 0.0, 25.0, 'Mercado'),
  ('PRO-135', 'Espagueti a la Bolognesa', 'COCINA', 0.0, 25.0, 'Mercado'),
  ('PRO-136', 'Espagueti al Alfredo Montado con Lomo Fino', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-137', 'Tallarín Saltado de Pollo', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-138', 'Milanesa de Pollo', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-139', 'Pollo con Champiñones', 'COCINA', 0.0, 35.0, 'Mercado'),
  ('PRO-140', 'Chicharrón de Pollo', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-141', 'Pechuga a la Plancha', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-142', 'Pollo frito', 'COCINA', 0.0, 28.0, 'Mercado'),
  ('PRO-143', 'Saltado de Pollo', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-144', 'Pollo a lo cordon blue', 'COCINA', 0.0, 35.0, 'Mercado'),
  ('PRO-145', 'Dieta de Pollo', 'COCINA', 0.0, 20.0, 'Mercado'),
  ('PRO-146', 'Sopa a la Minuta', 'COCINA', 0.0, 25.0, 'Mercado'),
  ('PRO-147', 'Sopa Criolla', 'COCINA', 0.0, 25.0, 'Mercado'),
  ('PRO-148', 'Tallarín Saltado de Carne', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-149', 'Lomo Saltado', 'COCINA', 0.0, 32.0, 'Mercado'),
  ('PRO-150', 'Lomo a la Plancha', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-151', 'Lomo Mar y Tierra', 'COCINA', 0.0, 48.0, 'Mercado'),
  ('PRO-152', 'Lomo Saltado a lo Pobre', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-153', 'Bistec a lo Pobre', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-154', 'Sándwich de Jamonada', 'COCINA', 0.0, 8.0, 'Mercado'),
  ('PRO-155', 'Sándwich Mixto', 'COCINA', 0.0, 9.0, 'Mercado'),
  ('PRO-156', 'Sándwich de Huevo Frito', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-157', 'Sándwich de Huevo Revuelto', 'COCINA', 0.0, 8.0, 'Mercado'),
  ('PRO-158', 'Sándwich de Queso', 'COCINA', 0.0, 6.0, 'Mercado'),
  ('PRO-159', 'Club Sándwich', 'COCINA', 0.0, 17.0, 'Mercado'),
  ('PRO-160', 'Triple (jamón, queso, tomate)', 'COCINA', 0.0, 15.0, 'Mercado'),
  ('PRO-161', 'Triple (pollo, huevo, jamón)', 'COCINA', 0.0, 20.0, 'Mercado'),
  ('PRO-162', 'Piqueo Madera Labrada', 'COCINA', 0.0, 70.0, 'Mercado'),
  ('PRO-163', 'Tequeños Regionales', 'COCINA', 0.0, 25.0, 'Mercado'),
  ('PRO-164', 'Tequeños con Queso', 'COCINA', 0.0, 15.0, 'Mercado'),
  ('PRO-165', 'Tequeños con Hot Dog', 'COCINA', 0.0, 15.0, 'Mercado'),
  ('PRO-166', 'Huevo Frito c/2 panes', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-167', 'Huevo Revuelto Simple c/2 panes', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-168', 'Huevo Revuelto Mixto c/2 panes', 'COCINA', 0.0, 8.0, 'Mercado'),
  ('PRO-169', 'Omelet Mixto c/2 panes', 'COCINA', 0.0, 8.0, 'Mercado'),
  ('PRO-170', 'Omelet Simple c/2 panes', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-171', 'Ceviche de Corvina', 'COCINA', 0.0, 25.0, 'Mercado'),
  ('PRO-172', 'Ceviche Mixto', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-173', 'Leche deTigre', 'COCINA', 0.0, 20.0, 'Mercado'),
  ('PRO-174', 'Arroz con Mariscos', 'COCINA', 0.0, 35.0, 'Mercado'),
  ('PRO-175', 'Chaufa con Mariscos', 'COCINA', 0.0, 35.0, 'Mercado'),
  ('PRO-176', 'Chicharrón Mixto', 'COCINA', 0.0, 35.0, 'Mercado'),
  ('PRO-177', 'Chicharrón de Pescado', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-178', 'Cecina sola', 'COCINA', 0.0, 15.0, 'Mercado'),
  ('PRO-179', 'Chorizo solo', 'COCINA', 0.0, 15.0, 'Mercado'),
  ('PRO-180', 'Porción de Patacones', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-181', 'Porción de Tacacho', 'COCINA', 0.0, 8.0, 'Mercado'),
  ('PRO-182', 'Porción de Maduro', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-183', 'Porción de Papas Fritas', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-184', 'Porción de Yuca', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-185', 'Porción de Arroz', 'COCINA', 0.0, 4.0, 'Mercado'),
  ('PRO-186', 'Porción de Ensalada', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-187', 'Ensalada de Fruta', 'COCINA', 0.0, 12.0, 'Mercado'),
  ('PRO-188', 'Panqueque', 'COCINA', 0.0, 12.0, 'Mercado'),
  ('PRO-189', 'Refresco Maracuyá', 'BEBIDAS', 0.0, 18.0, 'Mercado'),
  ('PRO-190', 'Refresco Uva', 'BEBIDAS', 0.0, 18.0, 'Mercado'),
  ('PRO-191', 'Refresco cocona', 'BEBIDAS', 0.0, 18.0, 'Mercado'),
  ('PRO-192', 'Refresco Maíz morado', 'BEBIDAS', 0.0, 18.0, 'Mercado'),
  ('PRO-193', 'Refresco camu camu', 'BEBIDAS', 0.0, 20.0, 'Mercado'),
  ('PRO-194', '1L Limonada', 'BEBIDAS', 0.0, 15.0, 'Mercado'),
  ('PRO-195', '1L Limonada Frozem', 'BEBIDAS', 0.0, 18.0, 'Mercado'),
  ('PRO-196', 'Cóctel de Uva', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-197', 'Cóctel de Cocona', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-198', 'Cóctel de Camu Camu', 'BAR', 0.0, 25.0, 'Mercado'),
  ('PRO-199', 'Cóctel de Maracuyá', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-200', 'Cóctel de Café', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-201', 'Piña colada', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-202', 'Algarrobina', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-203', 'Margarita corona', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-204', 'Pisco sour', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-205', 'Maracuyá sour', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-206', 'Colada Fresh', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-207', 'Tinto de verano', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-208', 'Chilcano de pisco', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-209', 'Chilcano de maracuyá', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-210', 'Negroni', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-211', 'Mojito', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-212', 'Machu picchu', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-213', 'Cuba libre', 'BAR', 0.0, 20.0, 'Mercado'),
  ('PRO-214', 'PISCINA', 'BAZAR', 0.0, 15.0, 'Mercado'),
  ('PRO-215', 'Chocman - Doble Manjar', 'GOLOSINAS', 0.0, 2.5, 'Inmaculada'),
  ('PRO-216', 'Mini Jet', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-217', 'Jet', 'GOLOSINAS', 0.0, 3.5, 'Mercado'),
  ('PRO-218', 'Sublime', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-219', 'Mini Sublime', 'GOLOSINAS', 0.0, 3.5, 'Mercado'),
  ('PRO-220', 'Sandwich (Helado)', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-221', 'Mini Sandwich (Helado)', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-222', 'Donito Tricolor', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-223', 'BB', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-224', 'Frio rico paleta', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-225', 'Frio rico cono', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-226', 'Bombones', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-227', 'Alaska', 'GOLOSINAS', 0.0, 4.0, 'Mercado'),
  ('PRO-228', 'Sin Parar Cono', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-229', 'Kit kat', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-230', 'Sin parar copa', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-231', 'Copa kabana', 'GOLOSINAS', 0.0, 3.5, 'Mercado'),
  ('PRO-232', 'Copa clasica', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-233', 'Sin parar paleta', 'GOLOSINAS', 0.0, 6.0, 'Mercado'),
  ('PRO-234', 'Toalla H Normal', 'BAZAR', 0.0, 1.5, 'Mercado'),
  ('PRO-235', 'Toalla H Diario', 'BAZAR', 0.0, 0.3, 'Mercado'),
  ('PRO-236', 'Papel H x Rollo', 'BAZAR', 0.0, 1.0, 'Mercado'),
  ('PRO-237', 'Curitas', 'BAZAR', 0.0, 0.5, 'Mercado'),
  ('PRO-238', 'Abanico', 'BAZAR', 0.0, 5.0, 'Mercado'),
  ('PRO-239', 'Tijera', 'BAZAR', 0.0, 3.0, 'Mercado'),
  ('PRO-240', 'Encendedor', 'BAZAR', 0.0, 1.0, 'Mercado'),
  ('PRO-241', 'Nescafé', 'BAZAR', 0.0, 6.0, 'Mercado'),
  ('PRO-242', 'Huevo Frito', 'COCINA', 0.0, 2.5, 'Mercado'),
  ('PRO-243', 'San Juan', 'COCINA', 0.0, 10.0, 'Mercado'),
  ('PRO-244', 'Porción Plátano Frito', 'BEBIDAS', 0.0, 7.0, 'Mercado'),
  ('PRO-245', '1/2 Limonada', 'BEBIDAS', 0.0, 7.5, 'Mercado'),
  ('PRO-246', 'Te de Anís', 'BEBIDAS', 0.0, 3.0, 'Mercado'),
  ('PRO-247', 'Paracetamol', 'BAZAR', 0.0, 0.5, 'Mercado'),
  ('PRO-248', 'Hamburguesa Simple', 'COCINA', 0.0, 15.0, 'Mercado'),
  ('PRO-249', 'Hamburguesa Royal', 'COCINA', 0.0, 18.0, 'Mercado'),
  ('PRO-250', 'Hamburguesa Cheese', 'COCINA', 0.0, 16.0, 'Mercado'),
  ('PRO-251', 'Tacu Tacu en Salsa de Mariscos', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-252', 'Tacu Tacu con Lomo Saltado', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-253', 'Tacu Tacu con Lomo a la Plancha', 'COCINA', 0.0, 40.0, 'Mercado'),
  ('PRO-254', 'Tacu Tacu con Pechuga a la Plancha', 'COCINA', 0.0, 30.0, 'Mercado'),
  ('PRO-256', 'Sandwich de Jamonada', 'COCINA', 0.0, 8.0, 'Mercado'),
  ('PRO-257', 'Sandwich Mixto', 'COCINA', 0.0, 9.0, 'Mercado'),
  ('PRO-258', 'Sandwich de Huevo Frito', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-259', 'Sandwich con Huevo revuelto', 'COCINA', 0.0, 8.0, 'Mercado'),
  ('PRO-260', 'Sandwich de Queso', 'COCINA', 0.0, 6.0, 'Mercado'),
  ('PRO-261', 'Te de Manzanilla', 'BEBIDAS', 0.0, 3.0, 'Mercado'),
  ('PRO-262', 'Te de Canela y Clavo', 'BEBIDAS', 0.0, 3.0, 'Mercado'),
  ('PRO-263', 'Te Puro', 'BEBIDAS', 0.0, 3.0, 'Mercado'),
  ('PRO-264', 'Café', 'BEBIDAS', 0.0, 4.0, 'Mercado'),
  ('PRO-265', 'Leche', 'BEBIDAS', 0.0, 4.0, 'Mercado'),
  ('PRO-266', 'Café con Leche', 'BEBIDAS', 0.0, 8.0, 'Mercado'),
  ('PRO-267', '1 L Jugo de Piña', 'BEBIDAS', 0.0, 20.0, 'Mercado'),
  ('PRO-268', '1/2 Jugo de Piña', 'BEBIDAS', 0.0, 10.0, 'Mercado'),
  ('PRO-269', '1 L Jugo de Papaya', 'BEBIDAS', 0.0, 20.0, 'Mercado'),
  ('PRO-270', '1/2 Jugo de Papaya', 'BEBIDAS', 0.0, 10.0, 'Mercado'),
  ('PRO-271', '1L Jugo Surtido', 'BEBIDAS', 0.0, 28.0, 'Mercado'),
  ('PRO-272', '1/2 Jugo Surtido', 'BEBIDAS', 0.0, 14.0, 'Mercado'),
  ('PRO-273', '1L Jugo Especial', 'BEBIDAS', 0.0, 28.0, 'Mercado'),
  ('PRO-274', '1/2 Jugo Especial', 'BEBIDAS', 0.0, 14.0, 'Mercado'),
  ('PRO-275', '1L Jugo Batido (Platano/Leche)', 'BEBIDAS', 0.0, 24.0, 'Mercado'),
  ('PRO-276', '1/2  Jugo Batido (Platano/Leche)', 'BEBIDAS', 0.0, 12.0, 'Mercado'),
  ('PRO-277', 'Pilsen en Botella', 'BEBIDAS', 0.0, 10.0, 'Mercado'),
  ('PRO-278', 'Cuzqueña Negra en Botella', 'BEBIDAS', 0.0, 12.0, 'Mercado'),
  ('PRO-279', 'Cuzqueña Trigo Dorada', 'BEBIDAS', 0.0, 11.0, 'Mercado'),
  ('PRO-280', '1/2 Refresco de Maracuya', 'BEBIDAS', 0.0, 9.0, 'Mercado'),
  ('PRO-281', '1/2 Refresco de Uva', 'BEBIDAS', 0.0, 9.0, 'Mercado'),
  ('PRO-282', '1/2 Refresco de Cocona', 'BEBIDAS', 0.0, 9.0, 'Mercado'),
  ('PRO-283', '1/2 Refresco de Maíz Morado', 'BEBIDAS', 0.0, 9.0, 'Mercado'),
  ('PRO-284', '1/2 Refresco de Camu Camu', 'BEBIDAS', 0.0, 10.0, 'Mercado'),
  ('PRO-285', '1/2 Limonada Frozem', 'BEBIDAS', 0.0, 9.0, 'Mercado'),
  ('PRO-286', 'Desayunos', 'COCINA', 0.0, 10.0, 'Mercado'),
  ('PRO-287', 'Pan', 'COCINA', 0.0, 0.5, 'Mercado'),
  ('PRO-288', 'Cerveza Cusqueña Trigo', 'BEBIDAS', 0.0, 11.0, 'Mercado'),
  ('PRO-289', 'Pollo - Menú', 'COCINA', 0.0, 5.0, 'Mercado'),
  ('PRO-290', 'Tilapia - Menú', 'COCINA', 0.0, 7.0, 'Mercado'),
  ('PRO-291', 'Tapers', 'COCINA', 0.0, 2.0, 'Mercado'),
  ('PRO-292', 'San Juan Botella', 'BEBIDAS', 0.0, 10.0, 'Mercado'),
  ('PRO-293', 'Soda V', 'GOLOSINAS', 0.0, 1.0, 'Inmaculada'),
  ('PRO-294', 'Te/Infusiones', 'BEBIDAS', 0.0, 3.0, 'Mercado'),
  ('PRO-295', 'Huevo duro o frito', 'COCINA', 0.0, 2.5, 'Mercado'),
  ('PRO-296', 'AGUA PERSONAL COCINA', 'BEBIDAS', 0.0, 4.0, 'COCINA'),
  ('PRO-298', 'INKA KOLA PERSONAL COCINA', 'BEBIDAS', 0.0, 5.0, 'COCINA'),
  ('PRO-299', 'COCA COLA PERSONAL COCINA', 'BEBIDAS', 0.0, 5.0, 'COCINA'),
  ('PRO-301', 'TENTACION', 'GOLOSINAS', 0.0, 1.5, 'IMACULADA'),
  ('PRO-302', 'REPELENTE', 'BAZAR', 0.0, 3.5, 'Mercado'),
  ('PRO-303', 'TRIKIS', 'GOLOSINAS', 0.0, 2.0, 'Inmaculada'),
  ('PRO-304', 'Reyenito', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-305', 'GOMITAS', 'GOLOSINAS', 0.0, 2.5, 'Mercado'),
  ('PRO-306', 'MARSHMELLOW', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-307', 'MENTAS', 'GOLOSINAS', 0.0, 2.0, 'Mercado'),
  ('PRO-308', 'INVITE CHOCOLATE', 'GOLOSINAS', 0.0, 1.5, 'Mercado')
ON CONFLICT (codigo) DO UPDATE SET nombre=EXCLUDED.nombre, precio_venta=EXCLUDED.precio_venta;
